package com.checkinface.fragment.teacher_course.attendance_list

import com.checkinface.util.DateUtil

class AttendanceDataGenerator {
    companion object {
        fun loadData(): ArrayList<TeacherAttendanceModel> {
            val data = ArrayList<TeacherAttendanceModel>()
//            data.add(
//                TeacherAttendanceModel(
//                    DateUtil.getDate("2024-02-12T07:00:01+08:00"),
//                    3,
//                    2,
//                    1,
//                )
//            )
//            data.add(
//                TeacherAttendanceModel(
//                    DateUtil.getDate("2024-02-13T07:00:01+08:00"),
//                    1,
//                    4,
//                    2,
//                )
//            )
//            data.add(
//                TeacherAttendanceModel(
//                    DateUtil.getDate("2024-02-16T07:00:01+08:00"),
//                    12,
//                    5,
//                    4,
//                )
//            )
//            data.add(
//                TeacherAttendanceModel(
//                    DateUtil.getDate("2024-02-19T07:00:01+08:00"),
//                    63,
//                    23,
//                    12,
//                )
//            )
//            data.add(
//                TeacherAttendanceModel(
//                    DateUtil.getDate("2024-02-20T07:00:01+08:00"),
//                    0,
//                    0,
//                    0,
//                )
//            )
//            data.add(
//                TeacherAttendanceModel(
//                    DateUtil.getDate("2024-02-22T07:00:01+08:00"),
//                    5,
//                    3,
//                    1
//                )
//            )
//            data.add(
//                TeacherAttendanceModel(
//                    DateUtil.getDate("2024-02-25T07:00:01+08:00"),
//                    10,
//                    7,
//                    3
//                )
//            )
//            data.add(
//                TeacherAttendanceModel(
//                    DateUtil.getDate("2024-02-28T07:00:01+08:00"),
//                    15,
//                    10,
//                    5
//                )
//            )
//            data.add(
//                TeacherAttendanceModel(
//                    DateUtil.getDate("2024-03-02T07:00:01+08:00"),
//                    8,
//                    4,
//                    2
//                )
//            )
//            data.add(
//                TeacherAttendanceModel(
//                    DateUtil.getDate("2024-03-05T07:00:01+08:00"),
//                    20,
//                    15,
//                    8
//                )
//            )
//            data.add(
//                TeacherAttendanceModel(
//                    DateUtil.getDate("2024-03-08T07:00:01+08:00"),
//                    18,
//                    6,
//                    4
//                )
//            )
//            data.add(
//                TeacherAttendanceModel(
//                    DateUtil.getDate("2024-03-11T07:00:01+08:00"),
//                    22,
//                    8,
//                    2
//                )
//            )
//            data.add(
//                TeacherAttendanceModel(
//                    DateUtil.getDate("2024-03-14T07:00:01+08:00"),
//                    25,
//                    5,
//                    3
//                )
//            )
//            data.add(
//                TeacherAttendanceModel(
//                    DateUtil.getDate("2024-03-17T07:00:01+08:00"),
//                    20,
//                    10,
//                    7
//                )
//            )
//            data.add(
//                TeacherAttendanceModel(
//                    DateUtil.getDate("2024-03-20T07:00:01+08:00"),
//                    28,
//                    3,
//                    1
//                )
//            )
            return data
        }
    }
}
